metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.171, mac: '18:c0:4d:f0:26:9b', disk: nvme0n1, network_interface: eno1}
        # metal1: {ansible_host: 192.168.1.111, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: eno1}
        # metal2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal0: {ansible_host: 192.168.0.171, mac: '18:c0:4d:f0:26:9b', disk: nvme0n1, network_interface: eno1}
